name: Build Codap Prd

on:
  push:
    branches: [ master ]

jobs:

  build:
    uses: team-monolith-product/tmn-gh-actions/.github/workflows/build_v2.yml@main
    with:
      env: prd
      target: main
      propertyPath: image.tag
      updateTargets: |
        {
          "aws": {
            "imageName": "jce-ecr-codap-all-prd",
            "valueFilePath": ["codap-nginx/aws-apne2-prd-service.yaml"]
          }
        }

    secrets:
      MACHINE_TOKEN: ${{ secrets.MACHINE_TOKEN }}
