name: Build Codap Dev

on:
  push:
    branches: [ develop ]

jobs:

  build:
    uses: team-monolith-product/tmn-gh-actions/.github/workflows/build_v2.yml@develop
    with:
      env: dev
      target: develop
      propertyPath: image.tag
      updateTargets: |
        {
          "aws": {
            "imageName": "jce-ecr-codap-all-dev",
            "valueFilePath": ["codap-nginx/aws-apne2-dev-service.yaml"]
          }
        }

    secrets:
      MACHINE_TOKEN: ${{ secrets.MACHINE_TOKEN }}
